### ISSUE TITLE
gnuradio-companion 3.8.2.0 crash on open on windows

### ISSUE THREAD

**Issue by denis-sp** [conda-forge/gnuradio-feedstock#30]
Issue:

gnuradio-companion 3.8.2.0 crash on open on windows. Version 3.8.1 works fine.

(base) PS F:\apps\Conda> gnuradio-companion.exe
No such schema ?org.gnome.desktop.interface?
Traceback (most recent call last):
  File "F:\apps\Conda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\apps\Conda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\apps\Conda\Library\bin\gnuradio-companion.exe\__main__.py", line 102, in <module>
  File "F:\apps\Conda\Library\bin\gnuradio-companion.exe\__main__.py", line 95, in run_main
  File "F:\apps\Conda\lib\site-packages\gnuradio\grc\main.py", line 73, in main
    from .gui.Platform import Platform
  File "F:\apps\Conda\lib\site-packages\gnuradio\grc\gui\Platform.py", line 26, in <module>
    from . import canvas
  File "F:\apps\Conda\lib\site-packages\gnuradio\grc\gui\canvas\__init__.py", line 21, in <module>
    from .param import Param
  File "F:\apps\Conda\lib\site-packages\gnuradio\grc\gui\canvas\param.py", line 23, in <module>
    from .. import ParamWidgets, Utils, Constants
  File "F:\apps\Conda\lib\site-packages\gnuradio\grc\gui\ParamWidgets.py", line 66, in <module>
    add_style_provider()
  File "F:\apps\Conda\lib\site-packages\gnuradio\grc\gui\ParamWidgets.py", line 58, in add_style_provider
    dark_theme = have_dark_theme()
  File "F:\apps\Conda\lib\site-packages\gnuradio\grc\gui\ParamWidgets.py", line 49, in have_dark_theme
    ["gsettings", "get", "org.gnome.desktop.interface", "gtk-theme"]
  File "F:\apps\Conda\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "F:\apps\Conda\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['gsettings', 'get', 'org.gnome.desktop.interface', 'gtk-theme']' returned non-zero exit status 1.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ryanvolz** [comment]
I can confirm that I see also see this in a Windows VM, and that 3.8.1.0 is not affected even with the same GTK, etc. installed. I'll do a little more digging to see if I can figure out what's happening.

**Comment by ryanvolz** [comment]
Looks like an uncaught exception bug in 3.8.2.0 that mostly affects Windows and macOS. There's already an upstream fix: https://github.com/gnuradio/gnuradio/pull/3727. I'll pull that patch and make a new conda-forge build for 3.8.2.0. Stand by.

**Comment by ryanvolz** [comment]
Thanks for the report, @denis-sp! The PR should auto-merge once the build finishes in a couple hours, and then the packages will be up on the conda-forge repo a short while later.

**Comment by denis-sp** [comment]
I will test it once it's online.

**Comment by denis-sp** [comment]
It works fine. Though conda treat the previous build as latest.
