### ISSUE TITLE
"ModuleNotFoundError" notification window (No module named 'runtime_swig')

### ISSUE THREAD

**Issue by AlexanderGros** [conda-forge/gnuradio-feedstock#38]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.  

Issue: Running <code>gnuradio-companion</code> in the Anaconda prompt opens a small "ModuleNotFoundError" notification window (GRC does not start). OS is Win10. <br/>
Notification says:
<<
Cannot import gnuradio.
Is the Python path environment variable set correctly?
All OS: PYTHONPATH

Is the library path environment variable set correctly?
Linux: LD_Library_Path
Windows: PATH

See https://wiki.gnuradio.org/index.php/ModuleNotFoundError

(No module named 'runtime_swig')
>>

<br/>
Environment (<code>conda list</code>):
<details>

```

$ conda list

# packages in environment at C:\Users\Alexander\anaconda3\envs\gnuradio:
#
# Name                    Version                   Build  Channel
adwaita-icon-theme        3.38.0               heaa5689_1    conda-forge
atk-1.0                   2.36.0               h7222f49_4    conda-forge
boost-cpp                 1.74.0               h54f0996_2    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cairo                     1.16.0            hba8bd2f_1007    conda-forge
certifi                   2020.12.5        py39hcbf5309_1    conda-forge
cffi                      1.14.4           py39h0878f49_1    conda-forge
chardet                   4.0.0            py39hcbf5309_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
codec2                    0.9.2                h301d43c_1    conda-forge
cryptography              3.3.1            py39h0878f49_1    conda-forge
epoxy                     1.5.5                h8d14728_0    conda-forge
fftw                      3.3.9           nompi_h9df19be_100    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
gdk-pixbuf                2.42.2               hd590532_2    conda-forge
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
glib                      2.66.4               he2d232f_1    conda-forge
gnuradio                  3.9.0.0          py39h70c6263_0    conda-forge
gnuradio-core             3.9.0.0          py39hd4f9262_0    conda-forge
gnuradio-grc              3.9.0.0          py39h856da1f_0    conda-forge
gnuradio-qtgui            3.9.0.0          py39hb757050_0    conda-forge
gnuradio-uhd              3.9.0.0          py39h6ff7f24_0    conda-forge
gnuradio-video-sdl        3.9.0.0          py39h856da1f_0    conda-forge
gnuradio-zeromq           3.9.0.0          py39h0fae580_0    conda-forge
gobject-introspection     1.66.1           py39hfe2e8ff_4    conda-forge
gsl                       2.6                  hdfb1a43_2    conda-forge
gtk3                      3.24.24              h3d55b94_1    conda-forge
hicolor-icon-theme        0.17                 h57928b3_2    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
libblas                   3.9.0                     7_mkl    conda-forge
libcblas                  3.9.0                     7_mkl    conda-forge
libclang                  11.0.1          default_h5c34c98_1    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libflac                   1.3.3                h0e60522_1    conda-forge
libglib                   2.66.4               h5320221_1    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0                     7_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
librsvg                   2.50.2               hca93135_2    conda-forge
libsndfile                1.0.30               h0e60522_1    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libtiff                   4.2.0                hc10be44_0    conda-forge
libusb                    1.0.24               h0e60522_0    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libxml2                   2.9.10               hf5bbc77_3    conda-forge
libxslt                   1.1.33               h65864e5_2    conda-forge
log4cpp                   1.1.3             ha925a31_1002    conda-forge
lxml                      4.6.2            py39h4fd7cdf_1    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mako                      1.1.4              pyh44b312d_0    conda-forge
markupsafe                1.1.1            py39hb82d6ee_3    conda-forge
menuinst                  1.4.16           py39hde42818_1    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mpir                      3.0.0             he025d50_1002    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
numpy                     1.19.5           py39h6635163_1    conda-forge
openssl                   1.1.1i               h8ffe710_0    conda-forge
pango                     1.42.4               hec34917_5    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
pycairo                   1.20.0           py39h8170971_1    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygobject                 3.38.0           py39h28dda48_4    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39hcbf5309_7    conda-forge
pyqt-impl                 5.12.3           py39h415ef7b_7    conda-forge
pyqt5-sip                 4.19.18          py39h415ef7b_7    conda-forge
pyqtchart                 5.12             py39h415ef7b_7    conda-forge
pyqtwebengine             5.12.1           py39h415ef7b_7    conda-forge
pysocks                   1.7.1            py39hcbf5309_3    conda-forge
python                    3.9.1           h7840368_3_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pywin32                   300              py39hb82d6ee_0    conda-forge
pyyaml                    5.4.1            py39hb82d6ee_0    conda-forge
pyzmq                     21.0.1           py39h6e08c89_0    conda-forge
qt                        5.12.9               h5909a2a_3    conda-forge
qwt                       6.1.5                h265ddaf_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
sdl                       1.2.15               h21ff451_1    conda-forge
setuptools                49.6.0           py39hcbf5309_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
tzdata                    2020f                he74cb21_0    conda-forge
uhd                       3.15.0.0         py39he0cccc2_5    conda-forge
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_2    conda-forge
volk                      2.4.1            py39h415ef7b_1    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_2    conda-forge
wincertstore              0.2             py39hcbf5309_1006    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zeromq                    4.3.3                h0e60522_3    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.8                h4e2f164_1    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```

$ conda info

     active environment : gnuradio
    active env location : C:\Users\Alexander\anaconda3\envs\gnuradio
            shell level : 2
       user config file : C:\Users\Alexander\.condarc
 populated config files : C:\Users\Alexander\.condarc
                          C:\Users\Alexander\anaconda3\envs\gnuradio\.condarc
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\Alexander\anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Alexander\anaconda3\pkgs
                          C:\Users\Alexander\.conda\pkgs
                          C:\Users\Alexander\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Alexander\anaconda3\envs
                          C:\Users\Alexander\.conda\envs
                          C:\Users\Alexander\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

```
</details>

**Comment by ryanvolz** [comment]
This is odd because gnuradio 3.9 doesn't use SWIG anymore and so it neither has nor should be looking for `runtime_swig`. My suspicion is that multiple installations (or perhaps leftovers from a previous installation) are getting mixed up. Give me a few minutes to work out some debug steps.

**Comment by ryanvolz** [comment]
Can you post the output of the following?

`echo %PATH%`

`where python`

`gnuradio-config-info --print-all`

Another thing to try is to remove (or temporarily rename) your GNU Radio configuration directory (you can get the location from `gnuradio-config-info --userprefsdir`, I think).

**Comment by AlexanderGros** [comment]
<code>echo %PATH%</code>
<details>

```
C:\Users\Alexander\anaconda3\envs\gnuradio;C:\Users\Alexander\anaconda3\envs\gnuradio\Library\mingw-w64\bin;C:\Users\Alexander\anaconda3\envs\gnuradio\Library\usr\bin;C:\Users\Alexander\anaconda3\envs\gnuradio\Library\bin;C:\Users\Alexander\anaconda3\envs\gnuradio\Scripts;C:\Users\Alexander\anaconda3\envs\gnuradio\bin;C:\Users\Alexander\anaconda3\condabin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\NoteBook FanControl;C:\texlive\2020\bin\win32;C:\Program Files\MiKTeX 2.9\miktex\bin\x64;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\80\Tools\Binn;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files\IVI Foundation\VISA\Win64\Bin;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn;C:\Program Files (x86)\IVI Foundation\IVI\bin;C:\Program Files\IVI Foundation\IVI\bin;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files\PuTTY;C:\Program Files (x86)\National Instruments\Shared\LabVIEW CLI;C:\Program Files\Inkscape\bin;C:\Program Files\GTK2-Runtime Win64\bin;C:\Users\Alexander\AppData\Local\Microsoft\WindowsApps;C:\Users\Alexander\AppData\Local\GitHubDesktop\bin;C:\Program Files (x86)\Nmap;C:\Users\Alexander\AppData\Local\Microsoft\WindowsApps;C:\Users\Alexander\anaconda3\Scripts;C:\Users\Alexander\anaconda3\envs\gnuradio;C:\Users\Alexander\anaconda3\Library\bin;C:\Users\Alexander\anaconda3;.
```

</details>

<br/>
<code>where python</code>
<details>

```
C:\Users\Alexander\anaconda3\envs\gnuradio\python.exe
C:\Program Files\Inkscape\bin\python.exe
C:\Users\Alexander\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Users\Alexander\anaconda3\python.exe
```

</details>

<br/>
<code>gnuradio-config-info --print-all</code>
<details>

```
C:/Users\Alexander\anaconda3\envs\gnuradio\Library\.
C:/Users\Alexander\anaconda3\envs\gnuradio\Library\etc
C:/Users\Alexander\anaconda3\envs\gnuradio\Library\etc\gnuradio\conf.d
C:\Users\Alexander\AppData\Roaming\.gnuradio
Tue, 19 Jan 2021 19:44:48
python-support;gnuradio-runtime;gr-ctrlport
3.9.0.0
1916
1916
C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe:::/MD /O2 /Ob2 /DNDEBUG /DWIN32 /D_WINDOWS /W3
C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe:::/MD /O2 /Ob2 /DNDEBUG /DWIN32 /D_WINDOWS /W3 /GR /EHsc
```
</details>

<br/>
For <code>gnuradio-config-info --userprefsdir</code> i have <code>C:\Users\Alexander\AppData\Roaming\.gnuradio</code>  but i do not find any .gnuradio folder in the roaming folder. I have a .gnuradio folder in <code>C:\Users\Alexander</code>

Thank you for the help.

**Comment by ryanvolz** [comment]
Those outputs look fine to me, so we'll have to keep digging. Maybe the next step is to see what preferences it's using, regardless of where it is pulling them from. Try `gnuradio-config-info --prefs`.

Something else we can try is to start importing parts of gnuradio in Python manually, and see if that reproduces the error or provides more information. For that, maybe try `python -c "from gnuradio import gr"`.

**Comment by AlexanderGros** [comment]
<code>python -c "from gnuradio import gr"</code>

<details>

```
Traceback (most recent call last):
  File "C:\Users\Alexander\Downloads\Win10-GQRX-GNU- User Interface\GNU-GUI\6\4\5\1\lib\python2.7\site-packages\gnuradio\gr\__init__.py", line 37, in <module>
    from runtime_swig import *
ModuleNotFoundError: No module named 'runtime_swig'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Alexander\Downloads\Win10-GQRX-GNU- User Interface\GNU-GUI\6\4\5\1\lib\python2.7\site-packages\gnuradio\gr\__init__.py", line 41, in <module>
    from runtime_swig import *
ModuleNotFoundError: No module named 'runtime_swig'
```
</details>

<br/>
So i erased the Win10-GQRX-GNU in the Downloads folder, were probably some remainings...

<br/>
Everything seems to work now. Thank you so much for the precious help !

**Comment by ryanvolz** [comment]
Huh. I don't know how that was getting in and interfering, but I'm glad you were able to solve it!

**Comment by ryanvolz** [comment]
For anybody who might find this in the future, better diagnostics to see if anything is modifying the path the Python used to import modules include:

`python -c "import sys; print('\n'.join(sys.path))"`

`echo %PYTHONPATH%` (Windows) or `echo $PYTHONPATH` (Linux/macOS)

If something other than you conda Python directory is first in the output of those, then you'll have to uninstall the interfering modules or modify your Python path. Google should be able to tell you how to do that.
